openapi: 3.0.0
info:
  description: >
    This is the document of vNotifier/vSANSlackbot restful API.

    Generating a API token is necessary before you start to use this APIs.

    Search vSANSlackbot Slack app, and click the button "Request API Token",
    you can get a unique token(without expiration unless you regenerate the token).

    This token is used as the bearer authorization in header.
    E.g. -H 'Authorization: Bearer 64a7def7e31d4e988f30387044dc2f52'
  version: 1.0.0-oas3
  title: vNotifier/vSANSlackbot Rest API
  contact:
    email: vsan-slackbot-team@vmware.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
components:
  schemas:
    Text:
      type: string
      example: This is the example message to be post via vNotifier APP
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT  
tags:
  - name: public
    description: Public vNotifier rest Api for VMware users
  - name: private
    description: Private vNotifier rest Api for vSANSlackbot admins
paths:
  /api/v1/channel/{channelID}/messages:
    post:
      security:
        - bearerAuth: []
      tags:
        - public
      summary: post message to a given channel via vNotifier APP
      operationId: postMessage
      description: >
        This API can be used to post message via vNotifier APP, even if you
        are not the administrator of the APP.

        Please request a bearer token on our vSANSlackbot APP for posting Slack
        message.

        If you want to post message to a private channel via vSANSlackbot,
        please make sure the APP has been invited to the target private channel.

        Pass the bearer token in header.
      parameters:
        - in: path
          name: channelID
          required: true
          type: string
          description: The channel ID to be sent
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Text'
            example:
              text: This is the example message to be post via vNotifier APP
              
        description: The text message need to be sent
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /api/v1/user/{userName}/messages:
    post:
      security:
      - Authorization: []
      tags:
      - public
      summary: post message to a given user name via vNotifier APP
      operationId: postMessage
      description: >
        This API can be used to post message to a given user name via 
        vNotifier APP, even if you are not the administrator of the APP.

        Please request a bearer token on vSANSlackbot APP for posting Slack 
        message. Pass the bearer token in header.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: userName
          required: true
          type: string
          description: The user name to be sent
          example: >
            Sixuan Yang's email address is ysixuan@vmware.com, 
            pick `ysixuan` as the user name. 
            
            Here is a way to get email address from Slack. Click slack user's 
            head icon and `View full profile`, then it show `Email address` on 
            Profile broad.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Text'
            example:
              text: This is the example message to be post via vNotifier APP
        description: The text message need to be sent
      responses:
        200:
          description: OK
        400:
          description: Bad Request
        401:
          description: Unauthorized
        500:
          description: Internal Server Error
  /api/v1/metrics:
    get:
      security:
        - bearerAuth: []
      tags:
        - private
      summary: Get metrics from vSANSlackbot server
      operationId: getMetrics
      description: >
        This internal API can be used to get metrics from vSANSlackbot server.
        It will response datas include number of sent report, number of enabled report
        by vSANSlackbot and number of API used times by vNotifier.

        After the metrics endpoint registered in chronus, we can setup the dashboard
        of each report type count. It will be easier for us to monitor slackbot service health.
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /api/v1/team_members/{teamCode}:
    get:
      security:
        - bearerAuth: []
      tags:
        - public
      summary: fetch the latest specific team members
      operationId: getMessage
      description: >
         This API can be used to get the latest specific team member list.

         Please request a bearer token on vSANSlackbot APP for posting Slack
         message. Pass the bearer token in header.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: teamCode
          in: path
          required: true
          type: string
          description: the team's code
          example: >
            <br>`vsan` is vSAN Team's code.<br>
            `vsan-zdom` is vSAN zDOM Team's code.<br>
            `vsan-fs` is vSAN VDFS Team's code.<br>
            `vsan-clom` is vSAN CLOM Team's code.<br>
            `vsan-health` is vSAN Health Team's code.
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /api/v1/team_members/{managerName}/all:
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - public
      summary: fetch all the members report to the given manager
      operationId: getMessage
      description: >
        This API can be used to get the latest members list of the given manager.
        The members list include all direct and indirect reporters.

        Please request a bearer token on vSANSlackbot APP for posting Slack
        message. Pass the bearer token in header.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: managerName
          in: path
          required: true
          type: string
          description: the manager's VMware ID
          example: >
            Zhou Huang's email address is zhouhuang@vmware.com,
            pick `zhouhuang` as the manager name.

            Here is a way to get email address from Slack. Click slack user's
            head icon and `View full profile`, then it show `Email address` on
            Profile broad.
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /api/v1/team_members/{managerName}/direct:
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - public
      summary: fetch the members direct report to the given manager
      operationId: getMessage
      description: >
        This API can be used to get the latest members list of the given manager.
        The members list only include direct reporters.

        Please request a bearer token on vSANSlackbot APP for posting Slack
        message. Pass the bearer token in header.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: managerName
          in: path
          required: true
          type: string
          description: the manager's VMware ID
          example: >
            Zhou Huang's email address is zhouhuang@vmware.com,
            pick `zhouhuang` as the manager name.

            Here is a way to get email address from Slack. Click slack user's
            head icon and `View full profile`, then it show `Email address` on
            Profile broad.
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
servers:
  - url: https://slackbot.vdp.oc.vmware.com/