apiVersion: v1
kind: Service
metadata:
  name: mongo-prd
  labels:
    name: mongo-prd
spec:
  type: NodePort
  selector:
    role: mongo-prd
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-prd
spec:
  selector:
    matchLabels:
      role: mongo-prd
      environment: product
  serviceName: "mongo"
  replicas: 1
  template:
    metadata:
      labels:
        role: mongo-prd
        environment: product
        sidecar.istio.io/inject: "true"
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
      - name: mongo-prd
        image: wcp-docker-local.artifactory.eng.vmware.com/mongo:4.0
        command: ["mongod"]
        args:
          - "--bind_ip"
          - "0.0.0.0"
          - "--smallfiles"
          - "--noprealloc"
          - "--auth"
        ports:
          - containerPort: 27017
        volumeMounts:
          - name: mongo-persistent-storage-prd
            mountPath: /data/db
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "400Mi"
            cpu: "400m"
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage-prd
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: tier0
      resources:
        requests:
          storage: 100Gi
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: slackbot-mongo-gateway
spec:
  selector:
    istio: ingressgateway-internal
  servers:
  - hosts:
    - slackbot-server-db.vdp.oc.vmware.com
    port:
      name: mongo
      number: 27017
      protocol: TCP
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: slackbot-mongo-virtualservice
spec:
  gateways:
  - slackbot-mongo-gateway
  hosts:
  - slackbot-server-db.vdp.oc.vmware.com
  tcp:
  - match:
    - port: 27017
    route:
    - destination:
        host: mongo-prd
        port:
          number: 27017