apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-discovery: enabled
    istio-injection: enabled
  name: vsanperf-external-database
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: vsanperf-external-database
spec:
  type: NodePort
  selector:
    app: mongo-prd
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-prd
  namespace: vsanperf-external-database
spec:
  selector:
    matchLabels:
      app: mongo-prd
      environment: product
  serviceName: "mongo-svc"
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-prd
        environment: product
        sidecar.istio.io/inject: "true"
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
      - name: mongo-prd
        image: wcp-docker-local.artifactory.eng.vmware.com/mongo:4.0
        command: ["mongod"]
        args:
          - "--bind_ip"
          - "0.0.0.0"
          - "--smallfiles"
          - "--noprealloc"
          - "--auth"
        ports:
          - containerPort: 27017
        volumeMounts:
          - name: db-storage
            mountPath: /data/db
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "400Mi"
            cpu: "400m"
  volumeClaimTemplates:
  - metadata:
      name: db-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: tier0
      resources:
        requests:
          storage: 20Gi
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: mongo-gateway
  namespace: vsanperf-external-database
spec:
  selector:
    istio: ingressgateway-internal
  servers:
  - hosts:
    - vsanperf-vsanbot-db.vdp.lvn.broadcom.net
    port:
      name: mongo
      number: 27017
      protocol: TCP
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: mongo-virtualservice
  namespace: vsanperf-external-database
spec:
  gateways:
  - mongo-gateway
  hosts:
  - vsanperf-vsanbot-db.vdp.lvn.broadcom.net
  tcp:
  - match:
    - port: 27017
    route:
    - destination:
        host: mongo-svc
        port:
          number: 27017