apiVersion: apps/v1
kind: Deployment
metadata:
  name: vsanbot-server
  namespace: vsanperf-vsanbot
spec:
  selector:
    matchLabels:
      app: vsanbot-server
  replicas: 1
  template:
    metadata:
      labels:
        app: vsanbot-server
        environment: product
    spec:
      securityContext:
        runAsUser: 175345366
        runAsGroup: 201
        fsGroup: 201
      containers:
        - name: vsanbot-server
          image: vsaninternaltools-docker-local.artifactory.vcfd.broadcom.net/product/slackbot/vsanbot-server:vdp
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MONGO_DB
              value: slackbot
            - name: MONGO_PORT
              value: "27017"
            - name: PORT
              value: "3000"
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
          - name: lvn-dbc2403
            mountPath: /slackbot/persist
          - name: build-apps
            mountPath: /build/apps/
          - name: build-toolchain
            mountPath: /build/toolchain/
          resources:
            requests:
              memory: "200Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "200m"
      volumes:
        - name: lvn-dbc2403
          nfs:
            server: lvn-dbc2403.lvn.broadcom.net
            path: /dbc/lvn-dbc2403/xl061876/public_html/slackbot/persist
        - name: build-toolchain
          nfs:
            server: nvlinas101.lvn.broadcom.net
            path: /ifs/nvlinas101/projects0371/toolchain
        - name: build-apps
          nfs:
            server: nvlinas101.lvn.broadcom.net
            path: /ifs/nvlinas101/projects0371/apps
---
apiVersion: v1
kind: Service
metadata:
  name: vsanbot-server
  namespace: vsanperf-vsanbot
spec:
  selector:
    app: vsanbot-server
  ports:
  - protocol: TCP
    port: 443
    targetPort: 3000
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: vsanbot-server
  namespace: vsanperf-vsanbot
  annotations:
    kubernetes.io/ingress.class: "vdp-contour-int"
spec:
  virtualhost:
    fqdn: vsanbot.vdp.lvn.broadcom.net
    tls:
      secretName: infra-system/vdp-int-domain-tls
  routes:
    - conditions:
        - prefix: /
      services:
        - name: vsanbot-server
          port: 443
      timeoutPolicy:
        response: 480s