apiVersion: apps/v1
kind: Deployment
metadata:
  name: slackbot-websocket-server-stg
  labels:
    app: slackbot-websocket-server-stg
spec:
  selector:
    matchLabels:
      app: slackbot-websocket-server-stg
  template:
    metadata:
      labels:
        app: slackbot-websocket-server-stg
        environment: staging
    spec:
      containers:
      - name: slackbot-websocket-server-stg
        image: vsaninternaltools-docker-local.artifactory.eng.vmware.com/stage/slackbot/slackbot-websocket-server:release-now
        imagePullPolicy: Always
        env:
        - name: MONGO_DB
          value: zoe-slackbot
        - name: MONGO_PORT
          value: "27017"
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "1000Mi"
            cpu: "400m"
        volumeMounts:
        - name: slackbot-nfs
          mountPath: /slackbot/persist
        - name: apps-volume
          mountPath: /build/apps
        - name: toolchain-volume
          mountPath: /build/toolchain
      securityContext:
        runAsUser: 10001
        runAsGroup: 10002
      volumes:
        - name: slackbot-nfs
          nfs:
            server: pa-archive.eng.vmware.com
            path: /slackbot-aas
        - name: apps-volume
          nfs:
            server: build-apps.eng.vmware.com
            path: /apps
        - name: toolchain-volume
          nfs:
            server: build-toolchain.eng.vmware.com
            path: /toolchain
