apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: slack-rest-api.svc-stage.ara.decc.vmware.com
  name: slack-rest-api-server
  labels:
    app.name: slack-rest-api-server
spec:
  type: LoadBalancer
  selector:
    app.name: slack-rest-api-server
  ports:
  - name: http
    port: 443
    targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack-rest-api-server
  labels:
    app.name: slack-rest-api-server
spec:
  selector:
    matchLabels:
      app.name: slack-rest-api-server
  replicas: 1
  template:
    metadata:
      labels:
        app.name: slack-rest-api-server
    spec:
      containers:
        - name: slack-rest-api-server
          image: shtest-docker-local.artifactory.eng.vmware.com/stage/slackbot/svs-monitor-for-rb:0.1.0
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          imagePullPolicy: Always
          ports:
            - containerPort: 443
          resources:
            requests:
              memory: "128Mi"
              cpu: "0.5"
            limits:
              memory: "128Mi"
              cpu: "0.5"
